### DISCUSSION TITLE
Animating the modal opening with path transitions

### DISCUSSION THREAD

**Discussion by wbobeirne** [shipshapecode/shepherd#1835] [Show and tell]
So I was running into some issues around transitioning from step to step cleanly while using `beforeShowPromise`, and I actually found that you can apply transitions to the modal's `path` element to have it animate between targets:

```css
.shepherd-modal-overlay-container path {
  transition: all 0.3s ease;
}
```
results in

https://user-images.githubusercontent.com/649992/156429770-72a12ced-c471-40e4-a998-34a6e984a580.mp4

Perhaps this should either be an option, added to the CSS by default, or maybe a cookbook entry? Either way, I thought it was cool and wanted to share.
